#version: "3.9"

services:
  app_blue:
    image: ${BLUE_IMAGE}
    environment:
      RELEASE_ID: ${RELEASE_ID_BLUE}
      APP_POOL: "blue"
      PORT: 3000
    ports:
      - "8081:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/healthz || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
    networks:
      - app_network

  app_green:
    image: ${GREEN_IMAGE}
    environment:
      RELEASE_ID: ${RELEASE_ID_GREEN}
      APP_POOL: "green"
      PORT: 3000
    ports:
      - "8082:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/healthz || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
    networks:
      - app_network

  nginx:
    image: nginx:1.25-alpine
    
    ports:
      - "8080:80"
    depends_on:
      - app_blue
      - app_green
    networks:
      - app_network
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./generate-nginx-conf.sh:/docker-entrypoint.d/generate-nginx-conf.sh:ro
      - ./nginx_logs:/var/log/nginx
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
    entrypoint: ["/bin/sh", "-c", "/docker-entrypoint.d/generate-nginx-conf.sh && nginx -g 'daemon off;'"]

  alert_watcher:
    build: .
    environment:
        SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
        ACTIVE_POOL: ${ACTIVE_POOL}
        ERROR_RATE_THRESHOLD: ${ERROR_RATE_THRESHOLD:-2}
        WINDOW_SIZE: ${WINDOW_SIZE:-200}
        ALERT_COOLDOWN_SEC: ${ALERT_COOLDOWN_SEC:-300}
    volumes:
      - ./watcher.py:/watcher.py
      - ./nginx_logs:/var/log/nginx:rw
    depends_on:
      - nginx
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  nginx_logs: